### PR TITLE
Some basic sanitation in install.sh

### PR DESCRIPTION
**Pull request by henkla**
Since '~' is an alias for '$HOME', I feel as if it would be a cleaner approach for pointing at the .bashrc file in the users home directory from within the install.sh file. Also, some whitespaces and whitetabs were removed from said file.

### CODE REVIEW

**Comment by henkla** [comment]
Funny how I actually wrote $HOME in commit message and git used my actual home directory in the message. That one's on me! :-)

**Comment by jthistle** [comment]
Thanks for the PR, but why replace the tilde? As you say, ~ is expanded to $HOME. The only time you need to explicitally use $HOME is if the tilde is quoted, which it isn't. You could argue code readability, but $HOME is just as readable as ~ to me...

**Comment by henkla** [comment]
I guess it comes down to views: in bash (which is where this is run), ~ will always point to the $HOME environmental variable. However, not necessarily for all shells. For that reason, I myself find it to be a good habit to use $HOME in scripts, instead of ~ in general.

In this scenario, it would make no differance. In broader perspectives and other cases it might.

**Comment by jthistle** [comment]
Eh, fair enough. In other shells, you'd be changing that RCFILE variable anyway, but doesn't matter. Merging this PR.

**Pull request merged**
